name: py36tf114k231

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - spyder
  - hvplot
  - jupyterlab
  - matplotlib
  - nodejs
  - pandas=0.24.2
  - pip
  - pip:
    - tensorflow-gpu==1.14
    - keras==2.3.1
    - jupytext==1.1.1
    - ipympl
  - scikit-learn
  - xeus-python
